# ASP.NET Core (.NET Framework)
# Build and test ASP.NET Core projects targeting the full .NET Framework.
# Add steps that publish symbols, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- main

pool:
  vmImage: 'windows-latest'

variables:
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'
  projectDirectory: 'DeployOnPremDemo'
  schemaDataDirectory: '$(Build.SourcesDirectory)\$(projectDirectory)\data'
  publishDirectory: '$(Build.ArtifactStagingDirectory)\_Publish'
  zipDirectory: '$(Build.ArtifactStagingDirectory)\_Zip'
  triggerDeployScript: $(Build.SourcesDirectory)\$(projectDirectory)\TriggerDeploy.ps1

steps:

# 1. Install NuGet
- task: NuGetToolInstaller@1

# 2. NuGet restore
- task: NuGetCommand@2
  inputs:
    restoreSolution: '$(solution)'

# 3. Build solutions
- task: VSBuild@1
  inputs:
    solution: '$(solution)'
    msbuildArgs: '/p:DeployOnBuild=true /p:WebPublishMethod=Package /p:PackageAsSingleFile=true /p:SkipInvalidConfigurations=true /p:DesktopBuildPackageLocation="$(build.artifactStagingDirectory)\WebApp.zip" /p:DeployIisAppPath="Default Web Site"'
    platform: '$(buildPlatform)'
    configuration: '$(buildConfiguration)'

# 4. Run tests
- task: VSTest@2
  inputs:
    platform: '$(buildPlatform)'
    configuration: '$(buildConfiguration)'

# 5. Include /data/* directory as part of the build output
- task: CopyFiles@2
  inputs:
    sourceFolder: $(schemaDataDirectory)
    targetFolder: '$(publishDirectory)'

# 6. Zip the build output
- task: ArchiveFiles@2
  inputs:
    rootFolderOrFile: '$(publishDir)'
    includeRootFolder: false
    archiveType: 'zip'
    archiveFile: '$(zipDirectory)/$(Build.BuildId).zip'
    replaceExistingArchive: true

# 7. Publish the zipped build output as an artifact
- task: PublishBuildArtifacts@1
  inputs:
    pathtoPublish: '$(zipDirectory)'
    artifactName: 'zip'
    publishLocation: 'Container'
    
# 7. Publish the TriggerDeploy.ps1 file
- task: PublishBuildArtifacts@1
  inputs:
    pathtoPublish: '$(triggerDeployScript)' 
    artifactName: 'triggerDeploy' 
    publishLocation: 'Container'
